### ISSUE TITLE
bro what is this? there is no MobileScanner :| you only added the clipper part(design), 

### ISSUE THREAD

**Issue by bhaskaraa45** [Govind-S-B/qr_scanner_overlay#2]
there is no MobileScanner widget only design is there
![Screenshot from 2023-12-28 01-40-37](https://github.com/Govind-S-B/qr_scanner_overlay/assets/115359430/f37eae52-8638-4b78-bf2d-89d87d9390f2)

**Comment by Govind-S-B** [comment]
Yeah that's exactly what I built , there was a pre existing qr scanner
library I just wanted a flexible overlay for it hence the scanner overlay
as the name says . I built this mainly cause I use it and a friend of mine
also wanted the same in his project so made it a package .

**Comment by Govind-S-B** [comment]
The usage also indicates that , sorry if it was now clear enough. 

https://github.com/Govind-S-B/qr_scanner_overlay?tab=readme-ov-file#usage

https://pub.dev/packages/mobile_scanner

**Comment by bhaskaraa45** [comment]
sorry got it, actually i searched for scanner i found it so i thought this is a scanner!
